server:
  port: 8090
spring:
  thymeleaf:
    cache: false
    freemarker:
      template-loader-path: classpath:/templates
      cache: false
      charset: UTF-8
      check-template-location: true
      content-type: text/html
      expose-request-attributes: false
      expose-session-attributes: false
      request-context-attribute: request
      suffix: .html
